services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=atendimentos
    volumes:
      - ./sus:/var/lib/postgresql/data:rw
    ports:
      - "8000:8000" 
    restart: always
  app:
    build: ./app
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - db
